apiVersion: v1
kind: Service
metadata:
  name: quiz-app
spec:
  selector:
    app: quiz-app
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-app
  labels: 
    app: quiz-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quiz-app
  template:
    metadata:
      labels:
        app: quiz-app
    spec:
      containers:
      - name: quiz-app
        image: agray998/quiz-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: secretkey
          valueFrom:
            secretKeyRef:
              name: quiz-app
              key: secretKey
        - name: databaseuri
          valueFrom:
            secretKeyRef:
              name: quiz-app
              key: databaseURI